Update profile format 1.4
BaseAdresseNationale/validateur-bal pull request #79
Opened 2023-09-27 06:04 UTC by fufeck

## Context

Avec la sortie du format bal 1.4 https://aitf-sig-topo.github.io/voies-adresses/#format-bal
Il y a maintenant 3 nouveau champs:
- id_ban_commune
- id_ban_toponyme
- id_ban_adresse

## Fonctionnalité

- Ajout de 2 nouveau profile par défaut `1.4` et `1.4-relax` qui sont des copies des `1.3`
- Ajout dans les profiles `1.4` de vérification que id_ban_commune / id_ban_toponyme / id_ban_adresse sont bien des uuidV4 et qu'ils sont bien unique sur une ligne.

2023-09-29 12:22 UTC, MaGOs92 requested changes

2023-10-02 05:36 UTC, fufeck commented on lib/schema/index.js
> +    addError('incoherence_id_ban')
J'ai renomé `incoherence_ids_ban` avec le label `Les ids ban renseignés ne sont pas cohérents avec les données de la base adresse nationale`
Cette erreur est pour signaler qu'une commune ne peut pas avoir le même id qu'un toponyme ou qu'une adresse

2023-10-02 05:37 UTC, fufeck commented on lib/schema/profiles/1.4-relax.js
> +  'id_ban_commune.type_invalide',
C'est un cas générale pour toute les erreurs lié aux ids_ban, de manière générale soit on met tous dans warning soit on met tous dans error, je vais voir avec notre équipe deja ;)

2023-11-02 08:43 UTC, MaGOs92 approved these changes
LGTM

2023-11-22 12:48 UTC, merged